extern const GeoLayout pik_helm_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout pik_helm_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout pik_helm_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout pik_helm_geo[];
extern Lights1 pik_helm_Helmet_lights;
extern Lights1 pik_helm_Light_lights;
extern Lights1 pik_helm_Metal__METAL__lights;
extern u8 pik_helm_bullymetal_ci8[];
extern u8 pik_helm_bullymetal_pal_rgba16[];
extern u8 pik_helm_Metal_Shade_rgba16_rgba16[];
extern u8 pik_helm_Metal_Light_rgba16_rgba16[];
extern Vtx pik_helm_Normal_Cap_DL_mesh_layer_5_vtx_0[61];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_5_tri_0[];
extern Vtx pik_helm_Normal_Cap_DL_mesh_layer_1_vtx_0[91];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx pik_helm_Normal_Cap_DL_mesh_layer_1_vtx_1[26];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_pik_helm_Helmet[];
extern Gfx mat_revert_pik_helm_Helmet[];
extern Gfx mat_pik_helm_Metal_Env_Map[];
extern Gfx mat_revert_pik_helm_Metal_Env_Map[];
extern Gfx mat_pik_helm_Light[];
extern Gfx mat_revert_pik_helm_Light[];
extern Gfx mat_pik_helm_Metal__METAL_[];
extern Gfx mat_revert_pik_helm_Metal__METAL_[];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_5[];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_5_mat_override_Metal__METAL__0[];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_1[];
extern Gfx pik_helm_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx pik_helm_material_revert_render_settings[];
