extern const GeoLayout pik_helm_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout pik_helm_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout pik_helm_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout pik_helm_wing_geo[];
extern Lights1 pik_helm_wing_Helmet_002_lights;
extern Lights1 pik_helm_wing_Light_002_lights;
extern Lights1 pik_helm_wing_Metal__METAL__lights;
extern u8 pik_helm_wing_bullymetal_ci8[];
extern u8 pik_helm_wing_bullymetal_pal_rgba16[];
extern u8 pik_helm_wing_Metal_Shade_rgba16_rgba16[];
extern u8 pik_helm_wing_Metal_Light_rgba16_rgba16[];
extern u8 pik_helm_wing_wing_2_ia8[];
extern u8 pik_helm_wing_wing1_ia8[];
extern Vtx pik_helm_wing_Wing_Cap_mesh_layer_5_vtx_0[61];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_5_tri_0[];
extern Vtx pik_helm_wing_Wing_Cap_mesh_layer_1_vtx_0[91];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx pik_helm_wing_Wing_Cap_mesh_layer_1_vtx_1[26];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx pik_helm_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx pik_helm_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx pik_helm_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx pik_helm_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_pik_helm_wing_Helmet_002[];
extern Gfx mat_revert_pik_helm_wing_Helmet_002[];
extern Gfx mat_pik_helm_wing_Metal_Env_Map_002[];
extern Gfx mat_revert_pik_helm_wing_Metal_Env_Map_002[];
extern Gfx mat_pik_helm_wing_Light_002[];
extern Gfx mat_revert_pik_helm_wing_Light_002[];
extern Gfx mat_pik_helm_wing_Metal__METAL_[];
extern Gfx mat_revert_pik_helm_wing_Metal__METAL_[];
extern Gfx mat_pik_helm_wing_Wing_Tip[];
extern Gfx mat_revert_pik_helm_wing_Wing_Tip[];
extern Gfx mat_pik_helm_wing_Wing_Base[];
extern Gfx mat_revert_pik_helm_wing_Wing_Base[];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_5[];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_5_mat_override_Metal__METAL__0[];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_1[];
extern Gfx pik_helm_wing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx pik_helm_wing_Wings_mesh_layer_4[];
extern Gfx pik_helm_wing_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx pik_helm_wing_material_revert_render_settings[];
